exp: concat

data:
  rna_path: datasets/TCGA-BRCA.star_counts.csv
  meth_path: datasets/TCGA-BRCA.methylation450.csv
  clinical_path: datasets/brca_pam50.csv

preprocess:
  rna_top_var: 2000
  meth_top_var: 2000

model:
  type: random_forest
  test_size: 0.2
  random_state: 42
  rf_n_estimators: 800
  rf_max_depth: null
  rf_min_samples_split: 2
  rf_min_samples_leaf: 1
  rf_max_features: sqrt
  rf_class_weight: balanced_subsample

mofa:
  factors: 20
